"""Choice-context generation for the controlled synthetic benchmark.

Paper alignment
---------------
This module constructs the context sets introduced in the Method section:

- ``X_sim``: simulation contexts used to elicit choices from candidate generators;
- ``X_H``: anchor contexts, implemented here as a subset of ``X_sim``;
- ``X_calib_int``: calibration-intervention contexts, generated by perturbing
  anchor-related contexts;
- ``X_cf``: held-out counterfactual/intervention contexts, never used to update
  the generator.

At this milestone we only generate and persist contexts.  The next milestone
will add a simulator ``pi_theta`` that maps ``(x, z)`` to a choice ``y``.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any
import json
from pathlib import Path

import numpy as np
import pandas as pd


DEFAULT_ATTRIBUTES: tuple[str, ...] = (
    "price",
    "quality",
    "sustain",
    "novelty",
    "brand",
)


@dataclass(frozen=True)
class ChoiceContextConfig:
    """Configuration for generated choice slates.

    Each context is a slate of ``n_alternatives`` alternatives.  Attributes are
    numeric and intentionally simple so they can be used directly by both the
    synthetic random-utility simulator and the MNL inner model in later steps.
    """

    n_sim_contexts: int = 100
    n_anchor_contexts: int = 50
    n_calib_intervention_contexts: int = 50
    n_cf_contexts: int = 50
    n_alternatives: int = 4
    attributes: tuple[str, ...] = DEFAULT_ATTRIBUTES
    price_intervention_multiplier: float = 1.20
    intervened_alternative_id: int = 0

    def __post_init__(self) -> None:
        if self.n_sim_contexts <= 0:
            raise ValueError("n_sim_contexts must be positive")
        if self.n_anchor_contexts <= 0:
            raise ValueError("n_anchor_contexts must be positive")
        if self.n_anchor_contexts > self.n_sim_contexts:
            raise ValueError("shared-context protocol requires n_anchor_contexts <= n_sim_contexts")
        if self.n_calib_intervention_contexts < 0:
            raise ValueError("n_calib_intervention_contexts must be non-negative")
        if self.n_calib_intervention_contexts > self.n_anchor_contexts:
            raise ValueError(
                "calibration interventions are generated from anchor contexts, so "
                "n_calib_intervention_contexts must be <= n_anchor_contexts"
            )
        if self.n_cf_contexts <= 0:
            raise ValueError("n_cf_contexts must be positive")
        if self.n_alternatives < 2:
            raise ValueError("n_alternatives must be at least 2")
        if not self.attributes:
            raise ValueError("attributes must be non-empty")
        if "price" not in self.attributes:
            raise ValueError("controlled synthetic benchmark expects a price attribute")
        if not (0 <= self.intervened_alternative_id < self.n_alternatives):
            raise ValueError("intervened_alternative_id must refer to an alternative in the slate")

    @classmethod
    def from_config(cls, section: dict[str, Any]) -> "ChoiceContextConfig":
        """Create context-generation settings from the ``benchmark`` config section."""

        return cls(
            n_sim_contexts=int(section.get("n_sim_contexts", 100)),
            n_anchor_contexts=int(section.get("n_anchor_contexts", 50)),
            n_calib_intervention_contexts=int(
                section.get("n_calib_intervention_contexts", 50)
            ),
            n_cf_contexts=int(section.get("n_cf_contexts", 50)),
            n_alternatives=int(section.get("n_alternatives", 4)),
            attributes=tuple(section.get("attributes", DEFAULT_ATTRIBUTES)),
            price_intervention_multiplier=float(section.get("price_intervention_multiplier", 1.20)),
            intervened_alternative_id=int(section.get("intervened_alternative_id", 0)),
        )

    def to_dict(self) -> dict[str, Any]:
        return {
            "n_sim_contexts": self.n_sim_contexts,
            "n_anchor_contexts": self.n_anchor_contexts,
            "n_calib_intervention_contexts": self.n_calib_intervention_contexts,
            "n_cf_contexts": self.n_cf_contexts,
            "n_alternatives": self.n_alternatives,
            "attributes": list(self.attributes),
            "price_intervention_multiplier": self.price_intervention_multiplier,
            "intervened_alternative_id": self.intervened_alternative_id,
        }


@dataclass(frozen=True)
class ContextSets:
    """Generated context sets used by the controlled synthetic benchmark."""

    x_sim: pd.DataFrame
    x_h: pd.DataFrame
    x_calib_int: pd.DataFrame
    x_cf: pd.DataFrame
    x_cf_base: pd.DataFrame
    config: ChoiceContextConfig

    def summary(self) -> dict[str, Any]:
        return {
            "config": self.config.to_dict(),
            "n_rows": {
                "X_sim": int(len(self.x_sim)),
                "X_H": int(len(self.x_h)),
                "X_calib_int": int(len(self.x_calib_int)),
                "X_cf": int(len(self.x_cf)),
                "X_cf_base": int(len(self.x_cf_base)),
            },
            "n_contexts": {
                "X_sim": int(self.x_sim["context_id"].nunique()),
                "X_H": int(self.x_h["context_id"].nunique()),
                "X_calib_int": int(self.x_calib_int["context_id"].nunique()),
                "X_cf": int(self.x_cf["context_id"].nunique()),
                "X_cf_base": int(self.x_cf_base["context_id"].nunique()),
            },
            "shared_context_protocol": {
                "X_H_subset_of_X_sim": True,
                "anchor_context_ids": sorted(self.x_h["context_id"].unique().tolist())[:10],
                "note": "Only the first 10 anchor context ids are shown in this summary.",
            },
        }

    def save_summary(self, path: str | Path) -> Path:
        out = Path(path)
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(json.dumps(self.summary(), indent=2, sort_keys=True), encoding="utf-8")
        return out


def _draw_attribute(name: str, rng: np.random.Generator, n: int) -> np.ndarray:
    """Draw one attribute for ``n`` alternatives.

    Feature ranges are intentionally bounded and interpretable:
    price is positive and roughly centered near 1, while non-price attributes are
    in [0, 1].  The brand coordinate is binary in the smoke benchmark.
    """

    if name == "price":
        return rng.uniform(0.50, 2.00, size=n)
    if name == "brand":
        return rng.binomial(1, 0.5, size=n).astype(float)
    return rng.uniform(0.0, 1.0, size=n)


def _generate_random_slates(
    *,
    prefix: str,
    n_contexts: int,
    n_alternatives: int,
    attributes: tuple[str, ...],
    rng: np.random.Generator,
    context_set: str,
) -> pd.DataFrame:
    records: list[dict[str, object]] = []
    for c in range(n_contexts):
        attr_values = {name: _draw_attribute(name, rng, n_alternatives) for name in attributes}
        for j in range(n_alternatives):
            rec: dict[str, object] = {
                "context_set": context_set,
                "context_id": f"{prefix}_{c:04d}",
                "context_index": c,
                "alternative_id": j,
                "product_id": f"item_{j:02d}",
                "base_context_id": "",
                "intervention_type": "none",
                "intervened_alternative_id": -1,
            }
            for name in attributes:
                rec[name] = float(attr_values[name][j])
            records.append(rec)
    return pd.DataFrame.from_records(records)


def _copy_with_context_set(df: pd.DataFrame, context_set: str) -> pd.DataFrame:
    out = df.copy()
    out["context_set"] = context_set
    return out


def _make_price_interventions(
    base: pd.DataFrame,
    *,
    prefix: str,
    context_set: str,
    n_contexts: int,
    multiplier: float,
    intervened_alternative_id: int,
) -> pd.DataFrame:
    selected_ids = sorted(base["context_id"].unique().tolist())[:n_contexts]
    selected = base[base["context_id"].isin(selected_ids)].copy()

    id_map = {old: f"{prefix}_{i:04d}" for i, old in enumerate(selected_ids)}
    selected["base_context_id"] = selected["context_id"]
    selected["context_id"] = selected["context_id"].map(id_map)
    selected["context_set"] = context_set
    selected["intervention_type"] = "price_increase"
    selected["intervened_alternative_id"] = int(intervened_alternative_id)

    mask = selected["alternative_id"].astype(int) == int(intervened_alternative_id)
    selected.loc[mask, "price"] = selected.loc[mask, "price"].astype(float) * float(multiplier)
    return selected.reset_index(drop=True)


def generate_context_sets(section: dict[str, Any], seed: int = 0) -> ContextSets:
    """Generate ``X_sim``, ``X_H``, ``X_calib_int``, and ``X_cf``.

    ``X_H`` follows the shared-context protocol: it is a subset of ``X_sim``.
    Calibration interventions are price perturbations of anchor-related
    contexts.  Held-out counterfactual contexts are generated from disjoint base
    slates and then perturbed in the same style.
    """

    cfg = ChoiceContextConfig.from_config(section)
    rng = np.random.default_rng(seed)

    x_sim = _generate_random_slates(
        prefix="sim",
        n_contexts=cfg.n_sim_contexts,
        n_alternatives=cfg.n_alternatives,
        attributes=cfg.attributes,
        rng=rng,
        context_set="X_sim",
    )
    anchor_ids = sorted(x_sim["context_id"].unique().tolist())[: cfg.n_anchor_contexts]
    x_h = _copy_with_context_set(x_sim[x_sim["context_id"].isin(anchor_ids)], "X_H")

    x_calib_int = _make_price_interventions(
        x_h,
        prefix="calib_int",
        context_set="X_calib_int",
        n_contexts=cfg.n_calib_intervention_contexts,
        multiplier=cfg.price_intervention_multiplier,
        intervened_alternative_id=cfg.intervened_alternative_id,
    )

    x_cf_base = _generate_random_slates(
        prefix="cf_base",
        n_contexts=cfg.n_cf_contexts,
        n_alternatives=cfg.n_alternatives,
        attributes=cfg.attributes,
        rng=rng,
        context_set="X_cf_base",
    )
    x_cf = _make_price_interventions(
        x_cf_base,
        prefix="cf",
        context_set="X_cf",
        n_contexts=cfg.n_cf_contexts,
        multiplier=cfg.price_intervention_multiplier,
        intervened_alternative_id=cfg.intervened_alternative_id,
    )

    return ContextSets(
        x_sim=x_sim.reset_index(drop=True),
        x_h=x_h.reset_index(drop=True),
        x_calib_int=x_calib_int,
        x_cf=x_cf,
        x_cf_base=x_cf_base.reset_index(drop=True),
        config=cfg,
    )
